version: "3.8"

services:
  api:
    build: ../
    container_name: detect_viewer_api
    ports:
      - 5000:5000
    env_file:
      - ../.env.development
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.19
    container_name: detect_viewer_db
    ports:
      - 5432:5432
    env_file:
      - ../.env.development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
